= influxdb-formula

https://travis-ci.com/saltstack-formulas/influxdb-formula[image:https://travis-ci.com/saltstack-formulas/influxdb-formula.svg?branch=master[Travis CI Build Status]]
https://github.com/semantic-release/semantic-release[image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg[Semantic Release]]

Formula to set up and configure influxdb.

== General notes

See the full
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[SaltStack
Formulas installation and usage instructions].

If you are interested in writing or contributing to formulas, please pay
attention to the
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas[Writing
Formula Section].

If you want to use this formula, please pay attention to the `FORMULA`
file and/or `git tag`, which contains the currently released version.
This formula is versioned according to http://semver.org/[Semantic
Versioning].

See
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning[Formula
Versioning Section] for more details.

== Contributing to this repo

*Commit message formatting is significant!!*

Please see
xref:main::CONTRIBUTING.adoc[How
to contribute] for more details.

== Available states

=== `influxdb`

Installs InfluxDB from [provided
packages](http://influxdb.com/download/).

At the moment you *have* to specify the InfluxDB version in the
`influxdb:version` pillar.

=== `influxdb.cli`

Installs the [influxdb-cli](https://github.com/phstc/influxdb-cli) gem
system wide.

=== `influxdb.config`

Renders the InfluxDB configuration from data provided in the
`influxdb:conf` pillar.

It requires the installation of the [toml Python
module](https://github.com/hit9/toml.py) via pip.

The formula ships with default configuration settings for various minor
versions of InfluxDB. That means that, if you define configuration
settings in your `influxdb.conf` pillar, your settings will be merged
with the default ones of that minor version. You can set
`influxdb:no_conf_defaults` in your pillar if you want to completely
specify the configuration yourself, without falling back to defaults.

== Testing

Linux testing is done with `kitchen-salt`.

=== Requirements

* Ruby
* Docker

[source,bash]
----
$ gem install bundler
$ bundle install
$ bin/kitchen test [platform]
----

Where `[platform]` is the platform name defined in `kitchen.yml`, e.g.
`debian-9-2019-2-py3`.

=== `bin/kitchen converge`

Creates the docker instance and runs the `influxdb` main state, ready
for testing.

=== `bin/kitchen verify`

Runs the `inspec` tests on the actual instance.

=== `bin/kitchen destroy`

Removes the docker instance.

=== `bin/kitchen test`

Runs all of the stages above in one go: i.e. `destroy` + `converge` +
`verify` + `destroy`.

=== `bin/kitchen login`

Gives you SSH access to the instance for manual testing.
